---
name: App-PerlCalc
version: 1.0.0
author:
  - 'David Caldwell <david@porkrind.org>'
abstract: Perl Calculator
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Script::Run: 0
recommends:
  Term::ReadLine: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
